<a href="https://colab.research.google.com/github/fboldt/aulasml/blob/master/aula07a_Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!unzip titanic.zip

Archive:  titanic.zip
  inflating: gender_submission.csv
  inflating: test.csv
  inflating: train.csv

In [2]:
import pandas as pd
df = pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [4]:
y = df['Survived']
X = df.drop('Survived', axis=1)

In [5]:
len(y)

891

In [6]:
for col in X.columns:
  print(f"{col:>12} {len(set(X[col])):4} {X[col].dtype}")

 PassengerId  891 int64
      Pclass    3 int64
        Name  891 object
         Sex    2 object
         Age  265 float64
       SibSp    7 int64
       Parch    7 int64
      Ticket  681 object
        Fare  248 float64
       Cabin  148 object
    Embarked    4 object

In [7]:
caracteristicas_indesejadas = ['PassengerId', 'Name', 'Ticket', 'Cabin']
Xdrop = X.drop(caracteristicas_indesejadas, axis=1)
Xdrop.columns

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked'], dtype='object')

In [8]:
Xnum = Xdrop.select_dtypes('number')
Xnum.columns

Index(['Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [9]:
for col in Xnum.columns:
  print(f"{col:>12} {Xnum[col].isnull().sum():2}")

      Pclass  0
         Age 177
       SibSp  0
       Parch  0
        Fare  0

In [11]:
Xnum[-5:]

     Pclass   Age  SibSp  Parch   Fare
886       2  27.0      0      0  13.00
887       1  19.0      0      0  30.00
888       3   NaN      1      2  23.45
889       1  26.0      0      0  30.00
890       3  32.0      0      0   7.75

In [13]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='median')
XnumTratado = imputer.fit_transform(Xnum)
XnumTratado[-5:]

array([[ 2.  , 27.  ,  0.  ,  0.  , 13.  ],
       [ 1.  , 19.  ,  0.  ,  0.  , 30.  ],
       [ 3.  , 28.  ,  1.  ,  2.  , 23.45],
       [ 1.  , 26.  ,  0.  ,  0.  , 30.  ],
       [ 3.  , 32.  ,  0.  ,  0.  ,  7.75]])

In [14]:
Xcat = Xdrop.select_dtypes(object)
Xcat.columns

Index(['Sex', 'Embarked'], dtype='object')

In [15]:
for col in Xcat.columns:
  print(f"{col:>12} {Xcat[col].isnull().sum():2}")

         Sex  0
    Embarked  2

In [16]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='most_frequent')
XcatTratado = imputer.fit_transform(Xcat)
XcatTratado[-5:]

array([['male', 'S'],
       ['female', 'S'],
       ['female', 'S'],
       ['male', 'C'],
       ['male', 'Q']], dtype=object)

In [17]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
XcatTratadoHot = encoder.fit_transform(XcatTratado)
XcatTratadoHot

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1782 stored elements and shape (891, 5)>

In [18]:
XcatTratadoHot.toarray()[-5:]

array([[0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [20]:
import numpy as np
Xtratado = np.c_[XnumTratado, XcatTratadoHot.toarray()]
Xtratado.shape

(891, 10)

In [26]:
from sklearn. base import BaseEstimator, TransformerMixin

class AtributosDesejados(BaseEstimator, TransformerMixin):
  def __init__(self):
    self.colunas_indesejadas = ['PassengerId', 'Name', 'Ticket', 'Cabin']
  def fit(self, X, y=None):
    return self
  def transform(self, X, y=None):
    return X.drop(self.colunas_indesejadas, axis=1)

atributos_desejados = AtributosDesejados()
Xdrop = atributos_desejados.fit_transform(X)
Xdrop.head()

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  22.0      1      0   7.2500        S
1       1  female  38.0      1      0  71.2833        C
2       3  female  26.0      0      0   7.9250        S
3       1  female  35.0      1      0  53.1000        S
4       3    male  35.0      0      0   8.0500        S

In [28]:
class AtributosNumericos(BaseEstimator, TransformerMixin):
  def fit(self, X, y=None):
    return self
  def transform(self, X, y=None):
    return X.select_dtypes(include='number')

atributos_numericos = AtributosNumericos()
Xnum = atributos_numericos.fit_transform(Xdrop)
Xnum[-5:]

     Pclass   Age  SibSp  Parch   Fare
886       2  27.0      0      0  13.00
887       1  19.0      0      0  30.00
888       3   NaN      1      2  23.45
889       1  26.0      0      0  30.00
890       3  32.0      0      0   7.75

In [29]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

pipenum = Pipeline([
    ('atributos_numericos', AtributosNumericos()),
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

XnumTratado = pipenum.fit_transform(Xdrop)
XnumTratado[-5:]

array([[-0.36936484, -0.18148724, -0.4745452 , -0.47367361, -0.38667072],
       [-1.56610693, -0.79628599, -0.4745452 , -0.47367361, -0.04438104],
       [ 0.82737724, -0.1046374 ,  0.43279337,  2.00893337, -0.17626324],
       [-1.56610693, -0.25833709, -0.4745452 , -0.47367361, -0.04438104],
       [ 0.82737724,  0.20276197, -0.4745452 , -0.47367361, -0.49237783]])

In [30]:
class AtributosCategoricos(BaseEstimator, TransformerMixin):
  def fit(self, X, y=None):
    return self
  def transform(self, X, y=None):
    return X.select_dtypes(include='object')

atributos_categoricos = AtributosCategoricos()
Xcat = atributos_categoricos.fit_transform(Xdrop)
Xcat[-5:]

        Sex Embarked
886    male        S
887  female        S
888  female        S
889    male        C
890    male        Q

In [31]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

pipecat = Pipeline([
    ('atributos_categoricos', AtributosCategoricos()),
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder())
])

XcatTratado = pipecat.fit_transform(Xdrop)
XcatTratado

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1782 stored elements and shape (891, 5)>

In [36]:
from sklearn.pipeline import FeatureUnion

unecaracteristicas = FeatureUnion([
    ('pipenum', pipenum),
    ('pipecat', pipecat)
])

Xtratado = unecaracteristicas.fit_transform(Xdrop)
Xtratado.shape

(891, 10)

In [46]:
class DenseTransformer(BaseEstimator, TransformerMixin):
  def fit(self, X, y=None, **fit_params):
    return self
  def transform(self, X, y=None, **fit_params):
    return X.toarray()

preproc = Pipeline([
    ('atributos_desejados', AtributosDesejados()),
    ('unecaracteristicas', unecaracteristicas),
    ('to_dense', DenseTransformer())
])

XcatTratado = preproc.fit_transform(X)
XcatTratado.shape

(891, 10)

In [55]:
from sklearn.ensemble import RandomForestClassifier

clf = Pipeline([
    ('preproc', preproc),
    ('classificador', RandomForestClassifier())
])

clf.fit(X, y)

Pipeline(steps=[('preproc',
                 Pipeline(steps=[('atributos_desejados', AtributosDesejados()),
                                 ('unecaracteristicas',
                                  FeatureUnion(transformer_list=[('pipenum',
                                                                  Pipeline(steps=[('atributos_numericos',
                                                                                   AtributosNumericos()),
                                                                                  ('imputer',
                                                                                   SimpleImputer(strategy='median')),
                                                                                  ('scaler',
                                                                                   StandardScaler())])),
                                                                 ('pipecat',
                                                                  Pipeline(steps=[('atributos_categoricos',
                                                                                   AtributosCategoricos()),
                                                                                  ('imputer',
                                                                                   SimpleImputer(strategy='most_frequent')),
                                                                                  ('encoder',
                                                                                   OneHotEncoder())]))])),
                                 ('to_dense', DenseTransformer())])),
                ('classificador', RandomForestClassifier())])

In [56]:
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')

y_pred = clf.predict(X)
accuracy_score(y, y_pred)

0.9797979797979798

In [57]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(clf, X, y)
print(f"{scores.mean()}\n{scores}")

0.8070052099679869
[0.76536313 0.81460674 0.85393258 0.7752809  0.8258427 ]

In [58]:
clf.fit(X, y)
Xtest = pd.read_csv('test.csv')
ypred = clf.predict(Xtest)
ypred

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1])

In [59]:
submission = pd.read_csv('gender_submission.csv')
submission['Survived'] = ypred
submission.to_csv('submission.csv', index=False)

In [60]:
from sklearn.ensemble import StackingClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold

from sklearn.linear_model import LogisticRegression, SGDClassifier, RidgeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.neural_network import MLPClassifier

base_estimators = [
    ('rf', RandomForestClassifier()),
    ('et', ExtraTreesClassifier()),
    ('mlp', MLPClassifier()),
    ('sgd', SGDClassifier()),
    ('ridge', RidgeClassifier()),
    ('knn', KNeighborsClassifier()),
    ('gnb', GaussianNB()),
    ('lr', LogisticRegression())
]

clf = StackingClassifier(
    estimators=base_estimators
)

model = Pipeline([
    ('preproc', preproc),
    ('clf', clf)
])

scores = cross_val_score(model, X, y, cv=StratifiedKFold(n_splits=5))
print(f"{scores.mean()}\n{scores}")

0.8238026489234826
[0.81564246 0.81460674 0.8258427  0.80337079 0.85955056]

In [62]:
model.fit(X, y)
y_stk_pred = model.predict(Xtest)
y_stk_pred

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0])

In [65]:
len(ypred)

418

In [66]:
sum(ypred != y_stk_pred)

np.int64(38)

In [67]:
submission = pd.read_csv('gender_submission.csv')
submission['Survived'] = y_stk_pred
submission.to_csv('submission_stk.csv', index=False)

In [70]:
model = Pipeline([
    ('preproc', preproc),
    ('classificador', MLPClassifier())
])

scores = cross_val_score(model, X, y, cv=StratifiedKFold(n_splits=5))
print(f"{scores.mean()}\n{scores}")

0.8215617349821104
[0.81005587 0.80898876 0.82022472 0.78651685 0.88202247]

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier

params = [
    {
        'hidden_layer_sizes': [(50,), (100,), (50, 50), (100, 50)],
        'activation': ['tanh', 'relu'],
        'solver': ['sgd', 'adam'],
        'alpha': [0.0001, 0.001, 0.01],
        'learning_rate_init': [0.001, 0.01]
    }
]

clf = GridSearchCV(MLPClassifier(max_iter=1000), param_grid=params, cv=5, verbose=2, n_jobs=-1)

model = Pipeline([
    ('preproc', preproc),
    ('clf', clf)
])

scores = cross_val_score(model, X, y, cv=StratifiedKFold(n_splits=5), verbose=2, n_jobs=-1)
print(f"{scores.mean()}\n{scores}")

In [72]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.11)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 13.2 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.8.0

In [73]:
import optuna
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.pipeline import Pipeline

def objective(trial):
    # Hyperparameters to tune for MLPClassifier
    hidden_layer_sizes_choice = trial.suggest_categorical('hidden_layer_sizes', [(50,), (100,), (50, 50), (100, 50, 25)])
    activation = trial.suggest_categorical('activation', ['tanh', 'relu'])
    solver = trial.suggest_categorical('solver', ['sgd', 'adam'])
    alpha = trial.suggest_loguniform('alpha', 1e-4, 1e-2)
    learning_rate_init = trial.suggest_loguniform('learning_rate_init', 1e-3, 1e-1)

    clf = MLPClassifier(
        hidden_layer_sizes=hidden_layer_sizes_choice,
        activation=activation,
        solver=solver,
        alpha=alpha,
        learning_rate_init=learning_rate_init,
        max_iter=1000, # Increased max_iter to ensure convergence
        random_state=42
    )

    model = Pipeline([
        ('preproc', preproc),
        ('clf', clf)
    ])

    # Evaluate the model using cross-validation
    scores = cross_val_score(model, X, y, cv=StratifiedKFold(n_splits=5), n_jobs=-1, verbose=0)
    return scores.mean()

# Create an Optuna study and optimize
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50, n_jobs=-1, show_progress_bar=True)

print("Number of finished trials: ", len(study.trials))
print("Best trial:")
trial = study.best_trial

print(f"  Value: {trial.value}")
print("  Params: ")
for key, value in trial.params.items():
    print(f"    {key}: {value}")

# Train the final model with the best parameters found by Optuna
best_mlp_clf = MLPClassifier(
    hidden_layer_sizes=trial.params['hidden_layer_sizes'],
    activation=trial.params['activation'],
    solver=trial.params['solver'],
    alpha=trial.params['alpha'],
    learning_rate_init=trial.params['learning_rate_init'],
    max_iter=1000,
    random_state=42
)

final_model = Pipeline([
    ('preproc', preproc),
    ('clf', best_mlp_clf)
])

final_model.fit(X, y)

# Make predictions on the test set with the best model
y_optuna_pred = final_model.predict(Xtest)

# Create submission file
submission_optuna = pd.read_csv('gender_submission.csv')
submission_optuna['Survived'] = y_optuna_pred
submission_optuna.to_csv('submission_optuna.csv', index=False)

print("Submission file 'submission_optuna.csv' created successfully.")

[I 2026-05-06 00:42:42,839] A new study created in memory with name: no-name-b9b83528-5650-4d9d-8651-ded5abd4fe74

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-05-06 00:42:56,518] Trial 1 finished with value: 0.8126357416358043 and parameters: {'hidden_layer_sizes': (100,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0021052867666084, 'learning_rate_init': 0.025486003049476923}. Best is trial 1 with value: 0.8126357416358043.
[I 2026-05-06 00:43:00,187] Trial 0 finished with value: 0.8069989328981231 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00435106955706256, 'learning_rate_init': 0.012084193668537682}. Best is trial 1 with value: 0.8126357416358043.
[I 2026-05-06 00:43:02,926] Trial 2 finished with value: 0.7935220639005712 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0005742833078845184, 'learning_rate_init': 0.004029140312027307}. Best is trial 1 with value: 0.8126357416358043.
[I 2026-05-06 00:43:16,640] Trial 4 finished with value: 0.7969116816270165 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0057251941055900665, 'learning_rate_init': 0.05605458319495052}. Best is trial 1 with value: 0.8126357416358043.
[I 2026-05-06 00:43:16,688] Trial 3 finished with value: 0.7924047454648171 and parameters: {'hidden_layer_sizes': (100, 50, 25), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.003931266373321332, 'learning_rate_init': 0.014331824082756477}. Best is trial 1 with value: 0.8126357416358043.
[I 2026-05-06 00:43:41,496] Trial 5 finished with value: 0.8069612704789405 and parameters: {'hidden_layer_sizes': (100,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.001182274653013659, 'learning_rate_init': 0.022828916581514005}. Best is trial 1 with value: 0.8126357416358043.
[I 2026-05-06 00:43:48,749] Trial 6 finished with value: 0.8002950222835981 and parameters: {'hidden_layer_sizes': (100,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.00040848284422315264, 'learning_rate_init': 0.002086925778285486}. Best is trial 1 with value: 0.8126357416358043.
[I 2026-05-06 00:44:32,758] Trial 7 finished with value: 0.8125980792166217 and parameters: {'hidden_layer_sizes': (100,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00016820160227373578, 'learning_rate_init': 0.00947615933540599}. Best is trial 1 with value: 0.8126357416358043.
[I 2026-05-06 00:44:34,921] Trial 9 finished with value: 0.8115121461301864 and parameters: {'hidden_layer_sizes': (100,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0015453492432901366, 'learning_rate_init': 0.02473648412182916}. Best is trial 1 with value: 0.8126357416358043.
[I 2026-05-06 00:44:39,443] Trial 8 finished with value: 0.7767057937354843 and parameters: {'hidden_layer_sizes': (100, 50, 25), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.005010194892624792, 'learning_rate_init': 0.0010827873381954892}. Best is trial 1 with value: 0.8126357416358043.
[I 2026-05-06 00:44:46,086] Trial 11 finished with value: 0.8058565061829139 and parameters: {'hidden_layer_sizes': (50,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.009297667067065018, 'learning_rate_init': 0.08971885052736571}. Best is trial 1 with value: 0.8126357416358043.
[I 2026-05-06 00:44:51,837] Trial 10 finished with value: 0.8204506936162199 and parameters: {'hidden_layer_sizes': (50,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00042517968272323296, 'learning_rate_init': 0.011238715019884387}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:44:54,960] Trial 12 finished with value: 0.7923859142552256 and parameters: {'hidden_layer_sizes': (100,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00012271191720022656, 'learning_rate_init': 0.0051491044523467545}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:45:00,407] Trial 13 finished with value: 0.8013370158809867 and parameters: {'hidden_layer_sizes': (50,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00011233386095743471, 'learning_rate_init': 0.0054761239873183905}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:45:03,136] Trial 14 finished with value: 0.8092084614901763 and parameters: {'hidden_layer_sizes': (50,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0003416455603859933, 'learning_rate_init': 0.03841098168951864}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:45:03,159] Trial 15 finished with value: 0.791287427029063 and parameters: {'hidden_layer_sizes': (50,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.0020413710588247937, 'learning_rate_init': 0.04151180818068144}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:45:08,746] Trial 16 finished with value: 0.8036218693114054 and parameters: {'hidden_layer_sizes': (50,), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.002422974847661424, 'learning_rate_init': 0.023597883109181914}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:45:09,478] Trial 17 finished with value: 0.7755696440901387 and parameters: {'hidden_layer_sizes': (50,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0007800325339265356, 'learning_rate_init': 0.020143131318358848}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:46:41,119] Trial 18 finished with value: 0.8002510827945516 and parameters: {'hidden_layer_sizes': (100, 50, 25), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.000741698820841774, 'learning_rate_init': 0.008992076706613157}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:46:43,064] Trial 19 finished with value: 0.8025171050153788 and parameters: {'hidden_layer_sizes': (100, 50, 25), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00024190640598189292, 'learning_rate_init': 0.006098542156829601}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:46:48,333] Trial 21 finished with value: 0.811461929571276 and parameters: {'hidden_layer_sizes': (100,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0026336990711289202, 'learning_rate_init': 0.05889021601635149}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:46:48,521] Trial 20 finished with value: 0.8002573598644153 and parameters: {'hidden_layer_sizes': (100,), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00020952125155682138, 'learning_rate_init': 0.09562378663389227}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:47:31,453] Trial 22 finished with value: 0.8148452702278576 and parameters: {'hidden_layer_sizes': (100,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00021974589273919957, 'learning_rate_init': 0.008945635947613263}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:47:36,482] Trial 24 finished with value: 0.7901387232439896 and parameters: {'hidden_layer_sizes': (100,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0003823102211120205, 'learning_rate_init': 0.0026937008014738936}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:47:37,404] Trial 23 finished with value: 0.8125980792166217 and parameters: {'hidden_layer_sizes': (100,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00020135061866142104, 'learning_rate_init': 0.009540233337193183}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:48:15,046] Trial 25 finished with value: 0.8114744837110038 and parameters: {'hidden_layer_sizes': (100,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0005481163181817045, 'learning_rate_init': 0.015637445674911314}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:48:22,199] Trial 26 finished with value: 0.8125980792166217 and parameters: {'hidden_layer_sizes': (100,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.0005584710128026561, 'learning_rate_init': 0.015936272359525803}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:48:27,475] Trial 27 finished with value: 0.7935346180402989 and parameters: {'hidden_layer_sizes': (50,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0011252192323350377, 'learning_rate_init': 0.007732705244663038}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:48:29,173] Trial 28 finished with value: 0.7957755319816708 and parameters: {'hidden_layer_sizes': (50,), 'activation': 'tanh', 'solver': 'adam', 'alpha': 0.0010669021987807015, 'learning_rate_init': 0.03455082868567541}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:48:30,372] Trial 29 finished with value: 0.8069989328981231 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'adam', 'alpha': 0.00034561437123583076, 'learning_rate_init': 0.03578708161605507}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:48:52,100] Trial 30 finished with value: 0.7980227229929069 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0002735412670324122, 'learning_rate_init': 0.0112941346515862}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:48:54,234] Trial 31 finished with value: 0.814838993157994 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.001582807078221214, 'learning_rate_init': 0.0036799406102158}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:49:22,422] Trial 33 finished with value: 0.8148201619484026 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0017346371786300277, 'learning_rate_init': 0.003109370352396276}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:49:24,931] Trial 32 finished with value: 0.8137216747222397 and parameters: {'hidden_layer_sizes': (100,), 'activation': 'tanh', 'solver': 'sgd', 'alpha': 0.00016668567829196396, 'learning_rate_init': 0.011686826839447469}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:49:48,292] Trial 34 finished with value: 0.8137028435126483 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.003203661180963384, 'learning_rate_init': 0.003208301087049634}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:49:49,670] Trial 35 finished with value: 0.8159437574540205 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0015278540323271012, 'learning_rate_init': 0.0029452876434868194}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:50:02,594] Trial 36 finished with value: 0.8136902893729208 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0017728256513503391, 'learning_rate_init': 0.0016955268515842236}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:50:03,635] Trial 37 finished with value: 0.8137028435126483 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0014458448237580467, 'learning_rate_init': 0.0019475798377915359}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:50:29,874] Trial 38 finished with value: 0.8182035026049841 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0007818967737611271, 'learning_rate_init': 0.004065603834345755}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:50:32,565] Trial 39 finished with value: 0.8170736300295023 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0008446676984643379, 'learning_rate_init': 0.003859715706279432}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:50:49,443] Trial 41 finished with value: 0.8103195028560668 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0007730657702666508, 'learning_rate_init': 0.0012257749256583514}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:50:50,933] Trial 40 finished with value: 0.804758018956751 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0008107202981480439, 'learning_rate_init': 0.006860210643813071}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:51:18,600] Trial 42 finished with value: 0.8137216747222397 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0004821242560792068, 'learning_rate_init': 0.004747005727951675}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:51:20,850] Trial 43 finished with value: 0.8148327160881301 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00045956919944271284, 'learning_rate_init': 0.004302542437416815}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:51:44,027] Trial 44 finished with value: 0.819327098110602 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0006464594914979927, 'learning_rate_init': 0.004106969514070339}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:51:45,460] Trial 45 finished with value: 0.8181846713953927 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.00065355629731547, 'learning_rate_init': 0.0024688346048169388}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:51:59,501] Trial 46 finished with value: 0.8170673529596385 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0009251375935907435, 'learning_rate_init': 0.002310607324232727}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:52:02,868] Trial 47 finished with value: 0.8170673529596385 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0006146935515101825, 'learning_rate_init': 0.002491465593417946}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:52:24,289] Trial 48 finished with value: 0.8193208210407382 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0006038927296083988, 'learning_rate_init': 0.003900919582659796}. Best is trial 10 with value: 0.8204506936162199.
[I 2026-05-06 00:52:26,437] Trial 49 finished with value: 0.8125855250768941 and parameters: {'hidden_layer_sizes': (50, 50), 'activation': 'relu', 'solver': 'sgd', 'alpha': 0.0006272900906287738, 'learning_rate_init': 0.004047944625349272}. Best is trial 10 with value: 0.8204506936162199.
Number of finished trials:  50
Best trial:
  Value: 0.8204506936162199
  Params:
    hidden_layer_sizes: (50,)
    activation: tanh
    solver: sgd
    alpha: 0.00042517968272323296
    learning_rate_init: 0.011238715019884387
Submission file 'submission_optuna.csv' created successfully.